### ISSUE TITLE
node:7.6 express module error

### ISSUE THREAD

**Issue by webos21** [IoTKETI/Mobius_Docker#2]
Attaching to mobius_docker_node_1, mobius_docker_mqtt_1, mobius_docker_db_1
db_1    | 2019-10-17 05:12:27+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 5.7.28-1debian9 started.
db_1    | 2019-10-17 05:12:28+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
db_1    | 2019-10-17 05:12:28+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 5.7.28-1debian9 started.
db_1    | 2019-10-17 05:12:28+00:00 [Note] [Entrypoint]: Initializing database files
db_1    | 2019-10-17T05:12:28.143688Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
db_1    | 2019-10-17T05:12:28.435791Z 0 [Warning] InnoDB: New log files created, LSN=45790
db_1    | 2019-10-17T05:12:28.484057Z 0 [Warning] InnoDB: Creating foreign key constraint system tables.
db_1    | 2019-10-17T05:12:28.542705Z 0 [Warning] No existing UUID has been found, so we assume that this is the first time that this server has been started. Generating a new UUID: b6e354cb-f09c-11e9-bc47-025000000001.
db_1    | 2019-10-17T05:12:28.545497Z 0 [Warning] Gtid table is not ready to be used. Table 'mysql.gtid_executed' cannot be opened.
db_1    | 2019-10-17T05:12:29.220611Z 0 [Warning] CA certificate ca.pem is self signed.
db_1    | 2019-10-17T05:12:29.275995Z 1 [Warning] root@localhost is created with an empty password ! Please consider switching off the --initialize-insecure option.
db_1    | 2019-10-17 05:12:31+00:00 [Note] [Entrypoint]: Database files initialized
db_1    | 2019-10-17 05:12:31+00:00 [Note] [Entrypoint]: Starting temporary server
db_1    | 2019-10-17 05:12:31+00:00 [Note] [Entrypoint]: Waiting for server startup
db_1    | 2019-10-17T05:12:31.763346Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
db_1    | 2019-10-17T05:12:31.764613Z 0 [Note] mysqld (mysqld 5.7.28) starting as process 81 ...
db_1    | 2019-10-17T05:12:31.767974Z 0 [Note] InnoDB: PUNCH HOLE support available
db_1    | 2019-10-17T05:12:31.768024Z 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
db_1    | 2019-10-17T05:12:31.768029Z 0 [Note] InnoDB: Uses event mutexes
db_1    | 2019-10-17T05:12:31.768032Z 0 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
db_1    | 2019-10-17T05:12:31.768035Z 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
db_1    | 2019-10-17T05:12:31.768038Z 0 [Note] InnoDB: Using Linux native AIO
db_1    | 2019-10-17T05:12:31.768304Z 0 [Note] InnoDB: Number of pools: 1
db_1    | 2019-10-17T05:12:31.768480Z 0 [Note] InnoDB: Using CPU crc32 instructions
db_1    | 2019-10-17T05:12:31.769834Z 0 [Note] InnoDB: Initializing buffer pool, total size = 128M, instances = 1, chunk size = 128M
db_1    | 2019-10-17T05:12:31.779078Z 0 [Note] InnoDB: Completed initialization of buffer pool
db_1    | 2019-10-17T05:12:31.780944Z 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
db_1    | 2019-10-17T05:12:31.795924Z 0 [Note] InnoDB: Highest supported file format is Barracuda.
db_1    | 2019-10-17T05:12:31.806291Z 0 [Note] InnoDB: Creating shared tablespace for temporary tables
db_1    | 2019-10-17T05:12:31.806359Z 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
db_1    | 2019-10-17T05:12:31.841587Z 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
db_1    | 2019-10-17T05:12:31.842406Z 0 [Note] InnoDB: 96 redo rollback segment(s) found. 96 redo rollback segment(s) are active.
db_1    | 2019-10-17T05:12:31.842446Z 0 [Note] InnoDB: 32 non-redo rollback segment(s) are active.
db_1    | 2019-10-17T05:12:31.843557Z 0 [Note] InnoDB: 5.7.28 started; log sequence number 2628227
db_1    | 2019-10-17T05:12:31.844135Z 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
db_1    | 2019-10-17T05:12:31.844387Z 0 [Note] Plugin 'FEDERATED' is disabled.
db_1    | 2019-10-17T05:12:31.845608Z 0 [Note] InnoDB: Buffer pool(s) load completed at 191017  5:12:31
db_1    | 2019-10-17T05:12:31.850895Z 0 [Note] Found ca.pem, server-cert.pem and server-key.pem in data directory. Trying to enable SSL support using them.
db_1    | 2019-10-17T05:12:31.850935Z 0 [Note] Skipping generation of SSL certificates as certificate files are present in data directory.
db_1    | 2019-10-17T05:12:31.851750Z 0 [Warning] CA certificate ca.pem is self signed.
db_1    | 2019-10-17T05:12:31.851808Z 0 [Note] Skipping generation of RSA key pair as key files are present in data directory.
db_1    | 2019-10-17T05:12:31.853773Z 0 [Warning] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
db_1    | 2019-10-17T05:12:31.860969Z 0 [Note] Event Scheduler: Loaded 0 events
db_1    | 2019-10-17T05:12:31.861514Z 0 [Note] mysqld: ready for connections.
db_1    | Version: '5.7.28'  socket: '/var/run/mysqld/mysqld.sock'  port: 0  MySQL Community Server (GPL)
db_1    | 2019-10-17 05:12:32+00:00 [Note] [Entrypoint]: Temporary server started.
db_1    | Warning: Unable to load '/usr/share/zoneinfo/iso3166.tab' as time zone. Skipping it.
db_1    | Warning: Unable to load '/usr/share/zoneinfo/leap-seconds.list' as time zone. Skipping it.
db_1    | Warning: Unable to load '/usr/share/zoneinfo/zone.tab' as time zone. Skipping it.
db_1    | Warning: Unable to load '/usr/share/zoneinfo/zone1970.tab' as time zone. Skipping it.
db_1    | 2019-10-17 05:12:35+00:00 [Note] [Entrypoint]: Creating database mobiusdb
db_1    | 
db_1    | 2019-10-17 05:12:35+00:00 [Note] [Entrypoint]: /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/mobius.sql
db_1    | 
db_1    | 
db_1    | 2019-10-17 05:12:35+00:00 [Note] [Entrypoint]: Stopping temporary server
db_1    | 2019-10-17T05:12:35.402586Z 0 [Note] Giving 0 client threads a chance to die gracefully
db_1    | 2019-10-17T05:12:35.402630Z 0 [Note] Shutting down slave threads
db_1    | 2019-10-17T05:12:35.402635Z 0 [Note] Forcefully disconnecting 0 remaining clients
db_1    | 2019-10-17T05:12:35.402639Z 0 [Note] Event Scheduler: Purging the queue. 0 events
db_1    | 2019-10-17T05:12:35.402734Z 0 [Note] Binlog end
db_1    | 2019-10-17T05:12:35.403342Z 0 [Note] Shutting down plugin 'ngram'
db_1    | 2019-10-17T05:12:35.403374Z 0 [Note] Shutting down plugin 'partition'
db_1    | 2019-10-17T05:12:35.403378Z 0 [Note] Shutting down plugin 'BLACKHOLE'
db_1    | 2019-10-17T05:12:35.403381Z 0 [Note] Shutting down plugin 'ARCHIVE'
db_1    | 2019-10-17T05:12:35.403383Z 0 [Note] Shutting down plugin 'PERFORMANCE_SCHEMA'
db_1    | 2019-10-17T05:12:35.403408Z 0 [Note] Shutting down plugin 'MRG_MYISAM'
db_1    | 2019-10-17T05:12:35.403410Z 0 [Note] Shutting down plugin 'MyISAM'
db_1    | 2019-10-17T05:12:35.403418Z 0 [Note] Shutting down plugin 'INNODB_SYS_VIRTUAL'
db_1    | 2019-10-17T05:12:35.403421Z 0 [Note] Shutting down plugin 'INNODB_SYS_DATAFILES'
db_1    | 2019-10-17T05:12:35.403423Z 0 [Note] Shutting down plugin 'INNODB_SYS_TABLESPACES'
db_1    | 2019-10-17T05:12:35.403425Z 0 [Note] Shutting down plugin 'INNODB_SYS_FOREIGN_COLS'
db_1    | 2019-10-17T05:12:35.403427Z 0 [Note] Shutting down plugin 'INNODB_SYS_FOREIGN'
db_1    | 2019-10-17T05:12:35.403428Z 0 [Note] Shutting down plugin 'INNODB_SYS_FIELDS'
db_1    | 2019-10-17T05:12:35.403430Z 0 [Note] Shutting down plugin 'INNODB_SYS_COLUMNS'
db_1    | 2019-10-17T05:12:35.403432Z 0 [Note] Shutting down plugin 'INNODB_SYS_INDEXES'
db_1    | 2019-10-17T05:12:35.403434Z 0 [Note] Shutting down plugin 'INNODB_SYS_TABLESTATS'
db_1    | 2019-10-17T05:12:35.403435Z 0 [Note] Shutting down plugin 'INNODB_SYS_TABLES'
db_1    | 2019-10-17T05:12:35.403437Z 0 [Note] Shutting down plugin 'INNODB_FT_INDEX_TABLE'
db_1    | 2019-10-17T05:12:35.403439Z 0 [Note] Shutting down plugin 'INNODB_FT_INDEX_CACHE'
db_1    | 2019-10-17T05:12:35.403441Z 0 [Note] Shutting down plugin 'INNODB_FT_CONFIG'
db_1    | 2019-10-17T05:12:35.403442Z 0 [Note] Shutting down plugin 'INNODB_FT_BEING_DELETED'
db_1    | 2019-10-17T05:12:35.403444Z 0 [Note] Shutting down plugin 'INNODB_FT_DELETED'
db_1    | 2019-10-17T05:12:35.403446Z 0 [Note] Shutting down plugin 'INNODB_FT_DEFAULT_STOPWORD'
db_1    | 2019-10-17T05:12:35.403448Z 0 [Note] Shutting down plugin 'INNODB_METRICS'
db_1    | 2019-10-17T05:12:35.403449Z 0 [Note] Shutting down plugin 'INNODB_TEMP_TABLE_INFO'
db_1    | 2019-10-17T05:12:35.403462Z 0 [Note] Shutting down plugin 'INNODB_BUFFER_POOL_STATS'
db_1    | 2019-10-17T05:12:35.403465Z 0 [Note] Shutting down plugin 'INNODB_BUFFER_PAGE_LRU'
db_1    | 2019-10-17T05:12:35.403466Z 0 [Note] Shutting down plugin 'INNODB_BUFFER_PAGE'
db_1    | 2019-10-17T05:12:35.403468Z 0 [Note] Shutting down plugin 'INNODB_CMP_PER_INDEX_RESET'
db_1    | 2019-10-17T05:12:35.403470Z 0 [Note] Shutting down plugin 'INNODB_CMP_PER_INDEX'
db_1    | 2019-10-17T05:12:35.403472Z 0 [Note] Shutting down plugin 'INNODB_CMPMEM_RESET'
db_1    | 2019-10-17T05:12:35.403474Z 0 [Note] Shutting down plugin 'INNODB_CMPMEM'
db_1    | 2019-10-17T05:12:35.403476Z 0 [Note] Shutting down plugin 'INNODB_CMP_RESET'
db_1    | 2019-10-17T05:12:35.403478Z 0 [Note] Shutting down plugin 'INNODB_CMP'
db_1    | 2019-10-17T05:12:35.403480Z 0 [Note] Shutting down plugin 'INNODB_LOCK_WAITS'
db_1    | 2019-10-17T05:12:35.403482Z 0 [Note] Shutting down plugin 'INNODB_LOCKS'
db_1    | 2019-10-17T05:12:35.403484Z 0 [Note] Shutting down plugin 'INNODB_TRX'
db_1    | 2019-10-17T05:12:35.403487Z 0 [Note] Shutting down plugin 'InnoDB'
db_1    | 2019-10-17T05:12:35.403575Z 0 [Note] InnoDB: FTS optimize thread exiting.
db_1    | 2019-10-17T05:12:35.404056Z 0 [Note] InnoDB: Starting shutdown...
db_1    | 2019-10-17T05:12:35.506894Z 0 [Note] InnoDB: Dumping buffer pool(s) to /var/lib/mysql/ib_buffer_pool
db_1    | 2019-10-17T05:12:35.507561Z 0 [Note] InnoDB: Buffer pool(s) dump completed at 191017  5:12:35
db_1    | 2019-10-17T05:12:36.827504Z 0 [Note] InnoDB: Shutdown completed; log sequence number 12607300
db_1    | 2019-10-17T05:12:36.830201Z 0 [Note] InnoDB: Removed temporary tablespace data file: "ibtmp1"
db_1    | 2019-10-17T05:12:36.830253Z 0 [Note] Shutting down plugin 'MEMORY'
db_1    | 2019-10-17T05:12:36.830259Z 0 [Note] Shutting down plugin 'CSV'
db_1    | 2019-10-17T05:12:36.830263Z 0 [Note] Shutting down plugin 'sha256_password'
db_1    | 2019-10-17T05:12:36.830265Z 0 [Note] Shutting down plugin 'mysql_native_password'
db_1    | 2019-10-17T05:12:36.830400Z 0 [Note] Shutting down plugin 'binlog'
db_1    | 2019-10-17T05:12:36.833699Z 0 [Note] mysqld: Shutdown complete
db_1    | 
db_1    | 2019-10-17 05:12:37+00:00 [Note] [Entrypoint]: Temporary server stopped
db_1    | 
db_1    | 2019-10-17 05:12:37+00:00 [Note] [Entrypoint]: MySQL init process done. Ready for start up.
db_1    | 
db_1    | 2019-10-17T05:12:37.605358Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
db_1    | 2019-10-17T05:12:37.606750Z 0 [Note] mysqld (mysqld 5.7.28) starting as process 1 ...
db_1    | 2019-10-17T05:12:37.609897Z 0 [Note] InnoDB: PUNCH HOLE support available
db_1    | 2019-10-17T05:12:37.609946Z 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
db_1    | 2019-10-17T05:12:37.609951Z 0 [Note] InnoDB: Uses event mutexes
db_1    | 2019-10-17T05:12:37.609954Z 0 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
db_1    | 2019-10-17T05:12:37.609957Z 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
db_1    | 2019-10-17T05:12:37.609960Z 0 [Note] InnoDB: Using Linux native AIO
db_1    | 2019-10-17T05:12:37.610243Z 0 [Note] InnoDB: Number of pools: 1
db_1    | 2019-10-17T05:12:37.610389Z 0 [Note] InnoDB: Using CPU crc32 instructions
db_1    | 2019-10-17T05:12:37.611807Z 0 [Note] InnoDB: Initializing buffer pool, total size = 128M, instances = 1, chunk size = 128M
db_1    | 2019-10-17T05:12:37.620531Z 0 [Note] InnoDB: Completed initialization of buffer pool
db_1    | 2019-10-17T05:12:37.622606Z 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
db_1    | 2019-10-17T05:12:37.637660Z 0 [Note] InnoDB: Highest supported file format is Barracuda.
db_1    | 2019-10-17T05:12:37.648748Z 0 [Note] InnoDB: Creating shared tablespace for temporary tables
db_1    | 2019-10-17T05:12:37.648820Z 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
db_1    | 2019-10-17T05:12:37.681635Z 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
db_1    | 2019-10-17T05:12:37.682762Z 0 [Note] InnoDB: 96 redo rollback segment(s) found. 96 redo rollback segment(s) are active.
db_1    | 2019-10-17T05:12:37.682799Z 0 [Note] InnoDB: 32 non-redo rollback segment(s) are active.
db_1    | 2019-10-17T05:12:37.684146Z 0 [Note] InnoDB: Waiting for purge to start
db_1    | 2019-10-17T05:12:37.734773Z 0 [Note] InnoDB: 5.7.28 started; log sequence number 12607300
db_1    | 2019-10-17T05:12:37.735154Z 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
db_1    | 2019-10-17T05:12:37.736199Z 0 [Note] Plugin 'FEDERATED' is disabled.
db_1    | 2019-10-17T05:12:37.741003Z 0 [Note] InnoDB: Buffer pool(s) load completed at 191017  5:12:37
db_1    | 2019-10-17T05:12:37.743617Z 0 [Note] Found ca.pem, server-cert.pem and server-key.pem in data directory. Trying to enable SSL support using them.
db_1    | 2019-10-17T05:12:37.743660Z 0 [Note] Skipping generation of SSL certificates as certificate files are present in data directory.
db_1    | 2019-10-17T05:12:37.744644Z 0 [Warning] CA certificate ca.pem is self signed.
db_1    | 2019-10-17T05:12:37.744712Z 0 [Note] Skipping generation of RSA key pair as key files are present in data directory.
db_1    | 2019-10-17T05:12:37.745186Z 0 [Note] Server hostname (bind-address): '*'; port: 3306
db_1    | 2019-10-17T05:12:37.745247Z 0 [Note] IPv6 is available.
db_1    | 2019-10-17T05:12:37.745261Z 0 [Note]   - '::' resolves to '::';
db_1    | 2019-10-17T05:12:37.745274Z 0 [Note] Server socket created on IP: '::'.
db_1    | 2019-10-17T05:12:37.746927Z 0 [Warning] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
db_1    | 2019-10-17T05:12:37.754111Z 0 [Note] Event Scheduler: Loaded 0 events
db_1    | 2019-10-17T05:12:37.754650Z 0 [Note] mysqld: ready for connections.
db_1    | Version: '5.7.28'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server (GPL)
db_1    | 2019-10-17T05:12:58.055923Z 2 [Note] Access denied for user 'root'@'localhost' (using password: NO)
mqtt_1  | 1571289178: mosquitto version 1.6.7 starting
mqtt_1  | 1571289178: Config loaded from /mosquitto/config/mosquitto.conf.
mqtt_1  | 1571289178: Opening ipv4 listen socket on port 1883.
mqtt_1  | 1571289178: Opening ipv6 listen socket on port 1883.
node_1  | module.js:472
node_1  |     throw err;
node_1  |     ^
node_1  | 
node_1  | Error: Cannot find module 'express'
node_1  |     at Function.Module._resolveFilename (module.js:470:15)
node_1  |     at Function.Module._load (module.js:418:25)
node_1  |     at Module.require (module.js:498:17)
node_1  |     at require (internal/module.js:20:19)
node_1  |     at Object.<anonymous> (/home/node/app/app.js:22:15)
node_1  |     at Module._compile (module.js:571:32)
node_1  |     at Object.Module._extensions..js (module.js:580:10)
node_1  |     at Module.load (module.js:488:32)
node_1  |     at tryModuleLoad (module.js:447:12)
node_1  |     at Function.Module._load (module.js:439:3)

**Comment by webos21** [comment]
Mobius_Docker/Mobius 폴더에서
  1) git clone https://github.com/IoTKETI/Mobius.git을 하고
  2) npm install 을 수행해야 함

해결!
